project:
  type: website
  output-dir: docs
  resources:
    - "Pokemon Dashboard/dashboard/**"
    - "Settlers of Catan/dashboard/**"

website:
  title: "Jacob Anderson"
  navbar:
    left:
      - href: professional/index.qmd
        text: Professional Projects
      - href: master/index.qmd
        text: Master's Capstone
      - href: fun/index.qmd
        text: For Fun


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
