project:
  type: website
  output-dir: docs

website:
  title: "Jacob Anderson"
  navbar:
    left:
      - href: mario/index.qmd
        text: Mario Party
      - href: league/index.qmd
        text: League of Legends
      - href: travel/index.qmd
        text: Travels


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



