project:
  type: website
  output-dir: docs

website:
  title: "Jacob Anderson"
  navbar:
    left:
      - href: professional/index.qmd
        text: Professional Projects
      - href: fun/index.qmd
        text: For Fun


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



