project:
  type: website

website:
  title: "Jacob Anderson"
  navbar:
    left:
      - href: work
        text: Work Experience
      - href: mario
        text: Mario Party
      - href: league
        text: League of Legends
      - href: travel
        text: Travels


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



